// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GridControlAutoGeneratedColumnsBehavior.cs" company="RHEA System S.A.">
// Copyright (c) 2020-2022 RHEA System S.A.
// 
// Author: Sam Gerené, Alex Vorobiev, Alexander van Delft, Nathanael Smiechowski, Antoine Théate.
// 
// This file is part of DEHPMatlab
// 
// The DEHPMatlab is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
// 
// The DEHPMatlab is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software Foundation,
// Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace DEHPMatlab.Behaviors
{
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using System.Windows;

    using DevExpress.Mvvm.UI.Interactivity;
    using DevExpress.Xpf.Grid;

    /// <summary>
    /// The <see cref="GridControlAutoGeneratedColumnsBehavior"/> handle the width of all newly generated columns
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class GridControlAutoGeneratedColumnsBehavior : Behavior<GridControl>
    {
        /// <summary>
        /// Register event handlers
        /// </summary>
        protected override void OnAttached()
        {
            base.OnAttached();
            this.AssociatedObject.AutoGeneratedColumns += this.AssociatedObjectOnAutoGeneratedColumns;
        }

        /// <summary>
        /// Unregister event handlers
        /// </summary>
        protected override void OnDetaching()
        {
            base.OnDetaching();
            this.AssociatedObject.CurrentItemChanged -= this.AssociatedObjectOnAutoGeneratedColumns;
        }

        /// <summary>
        /// Hides the name of the first column and set the best width to all columns of the associated <see cref="GridControl"/>
        /// </summary>
        /// <param name="sender">The event sender</param>
        /// <param name="e">The event args</param>
        private void AssociatedObjectOnAutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            e.Handled = true;

            var indexColumn = this.AssociatedObject.Columns.FirstOrDefault(x => x.FieldName is not null && x.FieldName == "index");

            if (indexColumn is null)
            {
                return;
            }

            indexColumn.Header = "";
            indexColumn.FieldName = "index";
            indexColumn.Width = 25;

            foreach (var column in this.AssociatedObject.Columns.Where(x => x != indexColumn).ToList())
            {
                column.Width = 50;
            }
        }
    }
}
